Use absolute module namespace to prevent conflict with Guard::Process
Guard has it's own Process class and when calling Process.kill will use the Process module/class under Guard which does not implement kill resulting in error like: NoMethodError: undefined method `wait2' for Guard::Process:Class.